### PR TITLE
Fix unittest

### PR DESCRIPTION
**Pull request by lizliz**
This branch has set up the unittest framework in all of hte files in the tests folder. 

One thing I *didn't* do was take time to think about meaningful tests.  But, the perk is that now it should be much easier to check the code when pushing new branches, especially if we get some better tests in there. 

@myersau3 , there are a few tests of yours that need some better tests, but you can poke around to see.  

For right now, I want to get at least the unittest framework pulled in so that we have better checks in the future. 

Another thing I didn't do was to cleanup the make file. Anyone know bash better than me and can write a better makefile? I'm think we want the makefile to 
- Update the documentation 
- Run unittests (possibly only with a flag so it doesn't do it every time? Happy to be convinced otherwise)
- Any other compatibility checks we might want?

### CODE REVIEW

**Comment by sarahtymochko** [comment]
@lizliz I'm getting a segmentation fault which I have no idea how to debug... Just to make sure I'm doing this correctly, I ran `python -m unittest` from the main repo where the test folder is. And I get `Segmentation fault: 11`

**Comment by sarahtymochko** [comment]
I tried running each of the test files separately and these are the issues I ran into:

1. test_MakeData.py: says it ran 0 tests
2. test_OrdinalPartition.py: `Segmentation fault: 11` <- seems to have something to do with numpy? maybe a version issue?
3. test_SLSP.py: `ModuleNotFoundError: No module named 'teaspoon.TDA.SLSP'`
4. test_classification.py: `ModuleNotFoundError: No module named 'svmutil'`

**Comment by lizliz** [comment]
Ok, so the test_MakeData.py having no tests to run is fine. In that case, all the tests that were in that file involved drawing figures, so I renamed the functions (`def Rossler(self)` instead of `def test_Rossler(self)`) so that we didn't have to deal with it.  If anyone wants to add better tests for that, it would be cool. Maybe I should make that a separate issue to deal with later. For the purposes of this pull request, doesn't really matter. 

.... now off to go figure out what's up with test_OrdinalPartition.py.....

**Comment by lizliz** [comment]
Ok, so i was getting an issue with test_OrdinalPartition.py (although I think it was different than yours?) but in my case, I upgraded networkx (was version 2.5, now is 2.6.2) and it fixed issues on my end.

**Comment by sarahtymochko** [comment]
Updating networkx still didn't fix the numpy issue I was having... Let me flight with it a bit more. i think it's just a version issue and I started a new github issue to add versions to the documentation. If I cant figure it out today I'll merge it anyways since it is working for at least one person and shouldn't break anything...

**Review by sarahtymochko — APPROVED** [review]
I'm still having a version issue and ripser is giving a seg fault. But I started a separate issue for this (#25 ) so we can deal with it later.

**Pull request merged**
